// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace CHGameplayTags
{
	CROSSVIEWHUNTER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Health);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Attack);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Defence);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_CritRate);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_FireDelay);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_ReloadDelay);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_ArmorPiercingDamage);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_CritDamage);
	
	CROSSVIEWHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HeadDamage);
};
